# Generated by Django 5.1 on 2024-09-02 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sclist', '0005_todo_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='status',
        ),
    ]
