# Generated by Django 5.1 on 2024-09-02 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sclist', '0008_remove_todo_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
