# Generated by Django 5.1 on 2024-09-03 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sclist', '0011_todo_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='date',
        ),
    ]
