# Generated by Django 5.1 on 2024-09-04 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sclist', '0015_contact_todo_contacts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='contacts',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
