# Generated by Django 5.1 on 2024-09-04 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sclist', '0016_remove_todo_contacts_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='todo',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='todos', to='sclist.contact'),
        ),
    ]
