# Generated by Django 5.1 on 2024-09-04 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sclist', '0017_contact_todo_contacts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='phone_number',
            new_name='phoneNumber',
        ),
    ]
