# Generated by Django 5.1 on 2024-09-05 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sclist', '0018_rename_phone_number_contact_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('TODO', 'To-do'), ('DO_TODAY', 'Do Today')], default='TODO', max_length=10),
        ),
    ]
