# Generated by Django 5.1 on 2024-09-06 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sclist', '0022_remove_todaytask_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todaytask',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='todaytasks', to='sclist.contact'),
        ),
    ]
