# Generated by Django 5.1 on 2024-09-06 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sclist', '0023_alter_todaytask_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todaytask',
            name='contacts',
            field=models.ManyToManyField(to='sclist.contact'),
        ),
    ]
