# Generated by Django 5.1 on 2024-09-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sclist', '0028_todo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='todaytask',
            name='status',
            field=models.CharField(choices=[('todo', 'ToDo'), ('todaytasks', 'TodayTasks')], default='todo', max_length=20),
        ),
    ]
