# Generated by Django 5.1 on 2024-09-07 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sclist', '0029_todaytask_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todaytask',
            name='status',
            field=models.CharField(choices=[('todo', 'ToDo'), ('todaytasks', 'TodayTasks')], default='todaytasks', max_length=20),
        ),
    ]
