# Generated by Django 5.1 on 2024-09-09 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sclist', '0030_alter_todaytask_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='contacts',
        ),
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('todos', 'To Do'), ('todaytasks', 'Today Tasks'), ('inProgress', 'In Progress'), ('done', 'Done')], max_length=50),
        ),
        migrations.AddField(
            model_name='todo',
            name='contacts',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
