# Generated by Django 5.1 on 2024-09-09 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sclist', '0031_remove_todo_contacts_alter_todo_status_todo_contacts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='contacts',
        ),
        migrations.AddField(
            model_name='todo',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='todos', to='sclist.contact'),
        ),
    ]
