# Generated by Django 5.1 on 2024-09-09 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sclist', '0032_remove_todo_contacts_todo_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='done',
            name='status',
            field=models.CharField(choices=[('todos', 'To Do'), ('todaytasks', 'Today Tasks'), ('inProgress', 'In Progress'), ('done', 'Done')], default='todos', max_length=50),
        ),
        migrations.AddField(
            model_name='inprogress',
            name='status',
            field=models.CharField(choices=[('todos', 'To Do'), ('todaytasks', 'Today Tasks'), ('inProgress', 'In Progress'), ('done', 'Done')], default='todos', max_length=50),
        ),
        migrations.AlterField(
            model_name='done',
            name='contacts',
            field=models.ManyToManyField(blank=True, to='sclist.contact'),
        ),
        migrations.AlterField(
            model_name='inprogress',
            name='contacts',
            field=models.ManyToManyField(blank=True, to='sclist.contact'),
        ),
        migrations.AlterField(
            model_name='todaytask',
            name='contacts',
            field=models.ManyToManyField(blank=True, to='sclist.contact'),
        ),
        migrations.AlterField(
            model_name='todaytask',
            name='status',
            field=models.CharField(choices=[('todos', 'To Do'), ('todaytasks', 'Today Tasks'), ('inProgress', 'In Progress'), ('done', 'Done')], default='todos', max_length=50),
        ),
        migrations.AlterField(
            model_name='todo',
            name='contacts',
            field=models.ManyToManyField(blank=True, to='sclist.contact'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('todos', 'To Do'), ('todaytasks', 'Today Tasks'), ('inProgress', 'In Progress'), ('done', 'Done')], default='todos', max_length=50),
        ),
    ]
