# Generated by Django 5.1 on 2024-10-30 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sclist', '0035_remove_inprogress_contacts_remove_inprogress_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='phoneNumber',
            new_name='phone_number',
        ),
    ]
